[pytest]
testpaths = tests
norecursedirs = .staging "Programmi di test" temp* .git .pytest_cache
filterwarnings =
    ignore::DeprecationWarning:fastapi.testclient
    ignore::DeprecationWarning:starlette.testclient
    ignore::UserWarning:fastapi.testclient
    ignore::UserWarning:starlette.testclient
